[package]
name = "armory"
version = "0.2.2"

[[targets]]
triple = "x86_64_linux"
path = "target/x86_64-unknown-linux-musl/release/armory"

[[targets]]
triple = "x86_64_windows"
path = "target/x86_64-pc-windows-msvc/release/armory.exe"
